import type { Metadata } from "next";
import { Roboto, Geist_Mono, Archivo_Black } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const display = Archivo_Black({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${geistMono.variable} ${display.variable} antialiased`}
      >
        <header className="border-b bg-[var(--accent)] text-[var(--accent-contrast)]">
          <nav className="max-w-6xl mx-auto flex gap-6 p-4 items-center">
            <a href="/" className="flex items-center gap-2" aria-label="HOOPS Trainer Home">
              <Image src="/logo.png" width={140} height={28} alt="HOOPS Trainer" priority />
            </a>
            <a href="/" className="hover:underline flex items-center gap-1"><span>🏠</span><span>Home</span></a>
            <a href="/library" className="hover:underline flex items-center gap-1"><span>📚</span><span>Library</span></a>
            <a href="/content-management" className="hover:underline flex items-center gap-1"><span>➕</span><span>Content Management</span></a>
            <a href="/plan-builder" className="hover:underline flex items-center gap-1"><span>🧩</span><span>Plan Builder</span></a>
          </nav>
        </header>
        <main className="max-w-6xl mx-auto px-4">{children}</main>
      </body>
    </html>
  );
}
