import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b bg-[var(--accent)] text-[var(--accent-contrast)]">
          <nav className="max-w-6xl mx-auto flex gap-6 p-4 items-center">
            <span className="font-semibold tracking-wide">🏀 HOOPS Trainer</span>
            <a href="/" className="hover:underline">Home</a>
            <a href="/library" className="hover:underline">Library</a>
            <a href="/content-management" className="hover:underline">Content Management</a>
            <a href="/plan-builder" className="hover:underline">Plan Builder</a>
          </nav>
        </header>
        <main className="max-w-6xl mx-auto px-4">{children}</main>
      </body>
    </html>
  );
}
